zookeeper:
  quorum: 10.60.156.93:2181,10.60.64.13:2181,10.60.83.19:2181
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://10.60.156.93:3306/scheduler
    username: zg
    password: zg123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: 258474202@qq.com
    password: ignbojzqmpjdcabe

im:
  url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=
  token: f79af9b0-590d-4f07-af69-8ac7482c7a67

email:
  system:
    "{
      '258474202@qq.com': 'ignbojzqmpjdcabe'
      }"
  manager: 258474202@qq.com

