// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package com.clubfactory.platform.scheduler.logger.grpc;

public interface DBConnReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduler.DBConnReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * jdbcUrl
   * </pre>
   *
   * <code>string jdbcUrl = 1;</code>
   */
  String getJdbcUrl();
  /**
   * <pre>
   **
   * jdbcUrl
   * </pre>
   *
   * <code>string jdbcUrl = 1;</code>
   */
  com.google.protobuf.ByteString
      getJdbcUrlBytes();

  /**
   * <pre>
   **
   * jdbcUser
   * </pre>
   *
   * <code>string jdbcUser = 2;</code>
   */
  String getJdbcUser();
  /**
   * <pre>
   **
   * jdbcUser
   * </pre>
   *
   * <code>string jdbcUser = 2;</code>
   */
  com.google.protobuf.ByteString
      getJdbcUserBytes();

  /**
   * <pre>
   **
   * jdbcPassword
   * </pre>
   *
   * <code>string jdbcPassword = 3;</code>
   */
  String getJdbcPassword();
  /**
   * <pre>
   **
   * jdbcPassword
   * </pre>
   *
   * <code>string jdbcPassword = 3;</code>
   */
  com.google.protobuf.ByteString
      getJdbcPasswordBytes();

  /**
   * <pre>
   **
   * jdbcType:MYSQL,PG
   * </pre>
   *
   * <code>string jdbcType = 4;</code>
   */
  String getJdbcType();
  /**
   * <pre>
   **
   * jdbcType:MYSQL,PG
   * </pre>
   *
   * <code>string jdbcType = 4;</code>
   */
  com.google.protobuf.ByteString
      getJdbcTypeBytes();

  /**
   * <pre>
   **
   * 连接超时时间
   * </pre>
   *
   * <code>int32 timeout = 5;</code>
   */
  int getTimeout();
}
