// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package com.clubfactory.platform.scheduler.logger.grpc;

public interface ExpireLogReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scheduler.ExpireLogReq)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * dirPath
   * </pre>
   *
   * <code>string dir = 1;</code>
   */
  java.lang.String getDir();
  /**
   * <pre>
   **
   * dirPath
   * </pre>
   *
   * <code>string dir = 1;</code>
   */
  com.google.protobuf.ByteString
  getDirBytes();

  /**
   * <pre>
   **
   * n days : n
   * </pre>
   *
   * <code>int32 nDays = 2;</code>
   */
  int getNDays();
}
