// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package com.clubfactory.platform.scheduler.logger.grpc;

public interface RetByteInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scheduler.RetByteInfo)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   *  byte data info
   * </pre>
   *
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
